# Generated by Django 5.2 on 2026-07-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('mask', 'Mask'), ('emotion', 'Emotion')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('roc_auc', models.FloatField(blank=True, null=True)),
                ('trained_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('model_path', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'ModelVersion',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image_name', models.CharField(blank=True, default='', max_length=255)),
                ('faces_detected', models.IntegerField(default=0)),
                ('mask_result', models.CharField(blank=True, default='', max_length=30)),
                ('mask_confidence', models.FloatField(blank=True, null=True)),
                ('emotion_result', models.CharField(blank=True, default='', max_length=30)),
                ('emotion_confidence', models.FloatField(blank=True, null=True)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('webcam', 'Webcam'), ('api', 'API')], default='upload', max_length=20)),
                ('mongo_prediction_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'DetectionLog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='DetectionLo_timesta_797557_idx'), models.Index(fields=['mask_result'], name='DetectionLo_mask_re_eb409c_idx'), models.Index(fields=['emotion_result'], name='DetectionLo_emotion_b8c110_idx')],
            },
        ),
    ]
